version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: dockerfile
    image: freshcraft-site:latest
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php-fpm
      SERVICE_TAGS: dev
    volumes:
      - shared-data:/var/www
      - laravel-storage:/var/www/storage
      - type: bind
        source: ./fpm/php.ini
        target: /etc/php/8.1/fpm/php.ini
    networks:
      - freshcraft

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - shared-data:/var/www
      - laravel-storage:/var/www/storage
      - ./nginx/:/etc/nginx/conf.d/
      - /opt/certs:/etc/nginx/certs
    networks:
      - freshcraft

networks:
  freshcraft:
    driver: bridge

volumes:
  shared-data:
  laravel-storage:

