version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: dockerfile
    image: freshcraft-site:latest
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php-fpm
      SERVICE_TAGS: dev
    volumes:
      - static-content:/var/www/public
      - laravel-storage:/var/www/storage
      - bootstrap-cache:/var/www/bootstrap/cache
    networks:
      - freshcraft

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-content:/var/www/public
      - ./nginx/:/etc/nginx/conf.d/
      - /opt/certs:/etc/nginx/certs
    networks:
      - freshcraft

networks:
  freshcraft:
    driver: bridge

volumes:
  static-content: 
  bootstrap-cache:
  laravel-storage:
