version: '3'
services:

  php-fpm:
    build:
      context: .
      dockerfile: dockerfile
    image: freshcraft-site:latest
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php-fpm
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - freshcraft

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
      - /opt/certs:/etc/nginx/certs
    networks:
      - freshcraft

#Docker Networks
networks:
  freshcraft:
    driver: bridge
